import Head from 'next/head'
import styles from '../styles/Admin.module.css'

export default function Admin() {
 
  return (
    <div className={styles.bodyAdmin}>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport"  content="width=device-width, initial-scale=1.0" />       
      </Head>  
   
         <ul className={styles.ulListContainer}>   
           <li>Admin Services</li>   
            <li>Data Entry</li>
            <li>Proofreading</li>
            <li>Audio Typing</li>
            <li>Dictation</li>
            <li>Document Creation</li>
            <li>Form Creation</li>
            <li>Starter Forms</li>
            <li>Stock Take</li>
            <li>Business Start Up</li>
            <li>Office Set Up</li>
            <li>Research</li>         
         </ul>
         
</div>
  )
}
