import Head from 'next/head'
import styles from '../styles/Bookkeeping.module.css'
import Image from 'next/image'
import Link from 'next/link'

export default function Bookkeeping() {
    return (
      <div className={styles.bodyBookkeeping}>        
            <Image             
                src="https://images.unsplash.com/photo-1506784693919-ef06d93c28d2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"                   
                priority={true}             
            />  
        <Head>
          <title>Bookkeeping</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <section className={styles.listWrapper}>      
          <h1 className={styles.listTitle}>Bookkeeping Services</h1> 

          <ol className={styles.list}> 
            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
                <a>
                <h2 className={styles.listLink__header}>
                  <span>Set up Accounting Software</span>
                </h2>
                <p className={styles.listLink__description}>
                Updating ...
                </p>
                </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Expenses / Invoicing / Receipts</span>
                </h2>
                <p className={styles.listLink__description}>
                  Updating ...    
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Reconcilliation</span>
                </h2>
                <p className={styles.listLink__description}>
                  bank, petty Cash, Supplier Statements etc  
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Manage Journals</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Self Assessment Guidance</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>preperation of Finacial Statements</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Spreadsheets Creation and Updating</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>
                      
          </ol>
        </section>          
      </div>
    )
  }


   
          
            
        
             
   