import Head from 'next/head'
import styles from '../styles/Bookkeeping.module.css'

export default function Bookkeeping() {
 
  return (
    <div className={styles.bodyBookkeeping}>
      <Head>
        <title>Bookkeeping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport"  content="width=device-width, initial-scale=1.0" />       
      </Head>  
   
         <ul className={styles.ulListContainer}>   
           <li>Bookkeeping Services</li>   
            <li>Accounting Software</li>
            <li>Expenses</li>
            <li>Invoicing</li>
            <li>Receipts</li>
            <li>Reconcilliation</li>
            <li>Banking</li>
            <li>Petty Cash </li>
            <li>Management</li>
            <li>Supplier Statements</li>
            <li>Manage Journals</li>
            <li>Guidance</li>
            <li>Self Assessment</li>             
            <li>Financial Statements</li>
            <li>Spreadsheets</li>
            <li>Creation and Updating</li>              
         </ul>         
</div>
  )
}
