import Head from 'next/head'
import styles from '../styles/Business.module.css'
import Image from 'next/image'
import Link from 'next/link'

export default function Business() {
    return (
      <div className={styles.bodyBusiness}>        
            <Image             
                src="https://images.unsplash.com/photo-1506784693919-ef06d93c28d2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"                   
                priority={true}             
            />  
        <Head>
          <title>Business</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <section className={styles.listWrapper}>      
          <h1 className={styles.listTitle}>Business Services</h1> 

          <ol className={styles.list}> 
            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
                <a>
                <h2 className={styles.listLink__header}>
                  <span>Inland Revenue</span>
                </h2>
                <p className={styles.listLink__description}>
                Updating ...
                </p>
                </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Office Support</span>
                </h2>
                <p className={styles.listLink__description}>
                  Updating ...    
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Accounts</span>
                </h2>
                <p className={styles.listLink__description}>
                  Updating ...   
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Spreadsheets</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Organisation</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Management</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Research</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Customer Services</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>
          </ol>
        </section>          
      </div>
    )
  }


   