import Head from 'next/head'
import styles from '../styles/Business.module.css'

export default function Business() {
 
  return (
    <div className={styles.bodyBusiness}>
      <Head>
        <title>Business</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport"  content="width=device-width, initial-scale=1.0" />       
      </Head>  
   
         <ul className={styles.ulListContainer}>   
           <li>Business Services</li>  
           <li>Business Services</li>   
           <li>Business Services</li>   
           <li>Business Services</li>   
           <li>Business Services</li>   
           <li>Business Services</li>             
         </ul>         
</div>
  )
}
