import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

         <div className={styles.homeContainer}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}           
                src="https://images.unsplash.com/photo-1504297050568-910d24c426d3?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80"
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"   
                priority={true}             
            />  
    
            <h1 className={`${styles['']} ${styles['home__h1']}`}>Admin Element</h1>          
            <h1 className={`${styles['textCenter']} ${styles['home__h1b']}`}>Every business and household has an element of admin.</h1> 
               <p className={`${styles['textCenter']} ${styles['home__p']}`}>
                  Let me focus on yours so you do not have to.
               </p>           
       </div>   

    <div className={styles.gridContainer}>
      <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}     
                src="https://images.unsplash.com/photo-1562240020-ce31ccb0fa7d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmlsbHN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"            
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h1 className={styles.landingText}>ADMIN</h1>    
        </div>
 
      <div className={styles.container}>
        <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}
                src="https://images.unsplash.com/photo-1587145820266-a5951ee6f620?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FsY3VsYXRvcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60"             
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h1 className={styles.landingText}>BOOKKEEPING</h1>    
        </div>      

        <div className={styles.container}>
        <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}
                src="https://images.unsplash.com/photo-1522968941782-e27ac665baa3?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDZ8fG9mZmljZSUyMHBsYW50c3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60"              
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h1 className={styles.landingText}>BUSINESS</h1>    
        </div>  

      <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}   
                src="https://images.unsplash.com/photo-1556020685-ae41abfc9365?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YmVkcm9vbXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"             
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h1 className={styles.landingText}>PERSONAL</h1>    
       </div>              
     </div>
  
     <div className={`${styles['homeContainer']} ${styles['mt1']}`}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}     
                src="https://images.unsplash.com/photo-1599689444589-133726281155?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8d2h5JTIwd2FpdHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" 
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"                
            />            
            <h1 className={`${styles['textCenter']} ${styles['home__h1']}`}>Why wait ?</h1>          
            <h1 className={`${styles['textCenter']} ${styles['home__h1b']}`}>Sole Trader, Limited, Start Up Etc</h1>           
            <p className={`${styles['textCenter']} ${styles['home__p']}`}>LETS GET STARTED</p>                      
    </div>

    <div className={styles.secTwo}>
       <p>Whether a one off, small or large job, short or
           long term project.<br/>Choose from one of the
           packages or contact me and we can discuss the
           package that is right for you.
        </p>
    </div>

    <div className={styles.gridContainer}>
        <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}               
                src="https://images.unsplash.com/photo-1497215728101-856f4ea42174?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8b2ZmaWNlJTIwcGxhbnRzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60"
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h3 className={styles.landingText2}>Ad hoc<br/> Project</h3>
            <h3 className={styles.landingText2}>One off job</h3>   
            <h3 className={styles.landingText2}>£40 per hour</h3>     
       </div>

      <div className={styles.container}>
        <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}
                src="https://images.unsplash.com/photo-1483058712412-4245e9b90334?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjV8fG9mZmljZSUyMHBsYW50c3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"              
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h3 className={styles.landingText2}>Small<br/>Project</h3>    
            <h3 className={styles.landingText2}>Approx 15 hrs</h3>   
            <h3 className={styles.landingText2}>£40 per hour</h3> 
        </div>      

      <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}                
                src="https://images.unsplash.com/photo-1497215728101-856f4ea42174?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8b2ZmaWNlJTIwcGxhbnRzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60"               
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h3 className={styles.landingText2}>Medium<br/>Project</h3>
            <h3 className={styles.landingText2}>Approx 25 hrs</h3>   
            <h3 className={styles.landingText2}>£40 per hour</h3>     
       </div>      

       <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}                
                src="https://images.unsplash.com/photo-1522968941782-e27ac665baa3?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDZ8fG9mZmljZSUyMHBsYW50c3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60"               
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h3 className={styles.landingText2}>Large<br/> Project</h3> 
            <h3 className={styles.landingText2}>Approx 35 hrs</h3>   
            <h3 className={styles.landingText2}>£40 per hour</h3> 
       </div>          
    </div>      

    <div className={`${styles['homeContainer']} ${styles['mt1']}`}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}          
                src="https://images.unsplash.com/photo-1504297050568-910d24c426d3?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80"
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"                
            /> 
              <h1 className={`${styles['textCenter']} ${styles['home__h1']}`}>Admin Element</h1>                     
              <h1 className={`${styles['textCenter']} ${styles['home__h1b']}`}>GET YOUR ADMIN <br/>&<br/> BOOKEEPING IN SHAPE</h1> 
              <p className={`${styles['textCenter']} ${styles['home__p']}`}>
                LETS GET STARTED
              </p>            
    </div>        

    <footer className={`${styles['footer__container']} ${styles['']}`}>
		
			<div className={styles.footercol}>
				<ul className={styles.footercol__ul__list}>
		  		<li>Admin Element</li>
			  	<li><span className='material-icons-outlined'>phone</span> 0203 718 0730</li>
					<li><span className='material-icons'>phone</span> 07930 342 485</li>
        	<li><span className='material-icons'>markunread</span> enquiries@adminelement.com</li>
				</ul>
			</div>		
    
		<div className={`${styles['']} ${styles['textCenter']} ${styles['footer__copyright']}`}>
			<p>&copy; 2022 Admin Element</p>
		</div>

	</footer>

</div>
  )
}
