import Head from 'next/head'
import styles from '../styles/Personal.module.css'
import Image from 'next/image'
import Link from 'next/link'

export default function Personal() {
    return (
      <div className={styles.bodyPersonal}>        
            <Image             
                src="https://images.unsplash.com/photo-1509023464722-18d996393ca8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8ZGFya3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60"
                // src="https://images.unsplash.com/photo-1556020685-ae41abfc9365?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YmVkcm9vbXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"     
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"                   
                priority={true}             
            />  
        <Head>
          <title>Personal</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <section className={styles.listWrapper}>      
          <h1 className={styles.listTitle}>Personal Services</h1> 

          <ol className={styles.list}> 
            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
                <a>
                <h2 className={styles.listLink__header}>
                  <span>Budgeting</span>
                </h2>
                <p className={styles.listLink__description}>
                Updating ...
                </p>
                </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Debt Collectors</span>
                </h2>
                <p className={styles.listLink__description}>
                  Updating ...    
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Filing</span>
                </h2>
                <p className={styles.listLink__description}>
                  Updating ...   
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Letter writing</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Organising Paperwork</span>
                </h2>
                <p className={styles.listLink__description}>
                   Hard copy and electronic    
                </p>
              </a>
              </Link>             
            </li>

            <li className={styles.listItem}>
              <Link href="/" className={styles.listLink}>
              <a>
                <h2 className={styles.listLink__header}>
                  <span>Household Paperwork Management</span>
                </h2>
                <p className={styles.listLink__description}>
                   Updating ...     
                </p>
              </a>
              </Link>             
            </li>
            
          </ol>
        </section>          
      </div>
    )
  }


   
   
        
       
                  
   